### ISSUE TITLE
Blacklist Command

### ISSUE THREAD

**Issue by MEGSystem** [MoonlightCapital/InviteDeleter#5]
The blacklist command does not work
![image](https://user-images.githubusercontent.com/39799614/56427829-86b72000-62bd-11e9-92d3-04be9450ebc0.png)

**Comment by MoonlightCapital** [comment]
Are you blindly copypasting code from my bot without setting proper variables? Looks like this in your case, considering the line number.

**Comment by MEGSystem** [comment]
oh I found the problem... I had to install sqlite3
