### ISSUE TITLE
Inviteme command bug

### ISSUE THREAD

**Issue by Miky88** [MoonlightCapital/InviteDeleter#6]
When I use inviteme command (in my self-hosted bot) it doesn't work if the server has too few channels

**Comment by MoonlightCapital** [comment]
what

**Comment by Miky88** [comment]
fixed

**Comment by MoonlightCapital** [comment]
I'll look into it as it might affect my main instance.

**Comment by MoonlightCapital** [comment]
Also um, what error does it give?

**Comment by Miky88** [comment]
Now Just works by using the Event branch so I close this issue.
